nama_lengkap = input('Masukkan Nama =\n')
nisn = input('Masukkan NISN =\n')
jenis_kelamin = input('Masukkan Jenis Kelamin =\n')
tanggal_lahir = input('Masukkan Tanggal Lahir =\n')
Nilai_B_Indo = int(input('Masukkan Nilai B Indo =\n'))
Nilai_Matematika = int(input('Masukkan Nilai Matematika =\n'))
Nilai_B_Inggris = int(input('Masukkan Nilai B Inggris =\n'))
Nilai_Ipa = int(input('Masukkan Nilai Ipa =\n'))
print('=== Data Siswa ===')
print('Namamu adalah = %s' %nama_lengkap)
print('NISN = %s' %nisn)
print('Jenis Kelamin = %s' %jenis_kelamin)
print('Tanggal Lahir = %s' %tanggal_lahir)
print('=== Data Nilai Siswa ===')
print('Nilai B Indo = %d' % Nilai_B_Indo)
print('Nilai Matematika = %d' %Nilai_Matematika)
print('Nilai B Inggris = %d' %Nilai_B_Inggris)
print('Nilai Ipa = %d' %Nilai_Ipa)
print('Jumlah Nilai = %d' % (Nilai_B_Indo + Nilai_Matematika + Nilai_B_Inggris + Nilai_Ipa))
print('Rata-rata Nilai = %d' % ((Nilai_B_Indo + Nilai_Matematika + Nilai_B_Inggris + Nilai_Ipa) / 4))